// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.1
// source: table/PlayerData.proto

package table

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurHeadId  int32   `protobuf:"varint,1,opt,name=curHeadId,proto3" json:"curHeadId,omitempty"`          //当前头像id
	CurSkinId  int32   `protobuf:"varint,2,opt,name=curSkinId,proto3" json:"curSkinId,omitempty"`          //当前皮肤id
	HeadIdList []int32 `protobuf:"varint,3,rep,packed,name=headIdList,proto3" json:"headIdList,omitempty"` //头像列表
	SkinIdList []int32 `protobuf:"varint,4,rep,packed,name=skinIdList,proto3" json:"skinIdList,omitempty"` //皮肤列表
}

func (x *UserSetting) Reset() {
	*x = UserSetting{}
	mi := &file_table_PlayerData_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSetting) ProtoMessage() {}

func (x *UserSetting) ProtoReflect() protoreflect.Message {
	mi := &file_table_PlayerData_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSetting.ProtoReflect.Descriptor instead.
func (*UserSetting) Descriptor() ([]byte, []int) {
	return file_table_PlayerData_proto_rawDescGZIP(), []int{0}
}

func (x *UserSetting) GetCurHeadId() int32 {
	if x != nil {
		return x.CurHeadId
	}
	return 0
}

func (x *UserSetting) GetCurSkinId() int32 {
	if x != nil {
		return x.CurSkinId
	}
	return 0
}

func (x *UserSetting) GetHeadIdList() []int32 {
	if x != nil {
		return x.HeadIdList
	}
	return nil
}

func (x *UserSetting) GetSkinIdList() []int32 {
	if x != nil {
		return x.SkinIdList
	}
	return nil
}

type Hero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                          //英雄id
	Star        int32   `protobuf:"varint,2,opt,name=star,proto3" json:"star,omitempty"`                      //星数
	Lv          int32   `protobuf:"varint,3,opt,name=lv,proto3" json:"lv,omitempty"`                          //等级
	SkillIdList []int32 `protobuf:"varint,4,rep,packed,name=skillIdList,proto3" json:"skillIdList,omitempty"` //技能id列表
	Exp         int32   `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`                        //经验
}

func (x *Hero) Reset() {
	*x = Hero{}
	mi := &file_table_PlayerData_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hero) ProtoMessage() {}

func (x *Hero) ProtoReflect() protoreflect.Message {
	mi := &file_table_PlayerData_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hero.ProtoReflect.Descriptor instead.
func (*Hero) Descriptor() ([]byte, []int) {
	return file_table_PlayerData_proto_rawDescGZIP(), []int{1}
}

func (x *Hero) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hero) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *Hero) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

func (x *Hero) GetSkillIdList() []int32 {
	if x != nil {
		return x.SkillIdList
	}
	return nil
}

func (x *Hero) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

type HeroModule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroList []*Hero `protobuf:"bytes,1,rep,name=heroList,proto3" json:"heroList,omitempty"` //英雄列表
}

func (x *HeroModule) Reset() {
	*x = HeroModule{}
	mi := &file_table_PlayerData_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroModule) ProtoMessage() {}

func (x *HeroModule) ProtoReflect() protoreflect.Message {
	mi := &file_table_PlayerData_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroModule.ProtoReflect.Descriptor instead.
func (*HeroModule) Descriptor() ([]byte, []int) {
	return file_table_PlayerData_proto_rawDescGZIP(), []int{2}
}

func (x *HeroModule) GetHeroList() []*Hero {
	if x != nil {
		return x.HeroList
	}
	return nil
}

type Modules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroModule *HeroModule `protobuf:"bytes,1,opt,name=heroModule,proto3" json:"heroModule,omitempty"` //英雄模块
}

func (x *Modules) Reset() {
	*x = Modules{}
	mi := &file_table_PlayerData_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Modules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Modules) ProtoMessage() {}

func (x *Modules) ProtoReflect() protoreflect.Message {
	mi := &file_table_PlayerData_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Modules.ProtoReflect.Descriptor instead.
func (*Modules) Descriptor() ([]byte, []int) {
	return file_table_PlayerData_proto_rawDescGZIP(), []int{3}
}

func (x *Modules) GetHeroModule() *HeroModule {
	if x != nil {
		return x.HeroModule
	}
	return nil
}

type PlayerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId    uint64       `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`      //玩家id
	PlayerName  string       `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`   //玩家名称
	Level       int32        `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`            //玩家等级
	Exp         uint32       `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`                //玩家经验
	Gold        uint64       `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"`              //金币
	Diamond     uint64       `protobuf:"varint,6,opt,name=diamond,proto3" json:"diamond,omitempty"`        //钻石
	UserSetting *UserSetting `protobuf:"bytes,7,opt,name=userSetting,proto3" json:"userSetting,omitempty"` //玩家设置
	Modules     *Modules     `protobuf:"bytes,8,opt,name=modules,proto3" json:"modules,omitempty"`         //各个模块数据
}

func (x *PlayerData) Reset() {
	*x = PlayerData{}
	mi := &file_table_PlayerData_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerData) ProtoMessage() {}

func (x *PlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_table_PlayerData_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerData.ProtoReflect.Descriptor instead.
func (*PlayerData) Descriptor() ([]byte, []int) {
	return file_table_PlayerData_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerData) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerData) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerData) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerData) GetGold() uint64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PlayerData) GetDiamond() uint64 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

func (x *PlayerData) GetUserSetting() *UserSetting {
	if x != nil {
		return x.UserSetting
	}
	return nil
}

func (x *PlayerData) GetModules() *Modules {
	if x != nil {
		return x.Modules
	}
	return nil
}

var File_table_PlayerData_proto protoreflect.FileDescriptor

var file_table_PlayerData_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22,
	0x89, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x48, 0x65, 0x61, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x63, 0x75, 0x72, 0x48, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x75, 0x72, 0x53, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x63, 0x75, 0x72, 0x53, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x68,
	0x65, 0x61, 0x64, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x0a, 0x68, 0x65, 0x61, 0x64, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x6b, 0x69, 0x6e, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x6e, 0x0a, 0x04, 0x48,
	0x65, 0x72, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x74, 0x61, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x76, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x6c, 0x76, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x70, 0x22, 0x35, 0x0a, 0x0a, 0x48,
	0x65, 0x72, 0x6f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x68, 0x65, 0x72,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x08, 0x68, 0x65, 0x72, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x3c, 0x0a, 0x07, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x31, 0x0a,
	0x0a, 0x68, 0x65, 0x72, 0x6f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x52, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x22, 0xfe, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x65, 0x78, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x61, 0x6d, 0x6f,
	0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e,
	0x64, 0x12, 0x34, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x73, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_table_PlayerData_proto_rawDescOnce sync.Once
	file_table_PlayerData_proto_rawDescData = file_table_PlayerData_proto_rawDesc
)

func file_table_PlayerData_proto_rawDescGZIP() []byte {
	file_table_PlayerData_proto_rawDescOnce.Do(func() {
		file_table_PlayerData_proto_rawDescData = protoimpl.X.CompressGZIP(file_table_PlayerData_proto_rawDescData)
	})
	return file_table_PlayerData_proto_rawDescData
}

var file_table_PlayerData_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_table_PlayerData_proto_goTypes = []any{
	(*UserSetting)(nil), // 0: table.UserSetting
	(*Hero)(nil),        // 1: table.Hero
	(*HeroModule)(nil),  // 2: table.HeroModule
	(*Modules)(nil),     // 3: table.Modules
	(*PlayerData)(nil),  // 4: table.PlayerData
}
var file_table_PlayerData_proto_depIdxs = []int32{
	1, // 0: table.HeroModule.heroList:type_name -> table.Hero
	2, // 1: table.Modules.heroModule:type_name -> table.HeroModule
	0, // 2: table.PlayerData.userSetting:type_name -> table.UserSetting
	3, // 3: table.PlayerData.modules:type_name -> table.Modules
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_table_PlayerData_proto_init() }
func file_table_PlayerData_proto_init() {
	if File_table_PlayerData_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_table_PlayerData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_table_PlayerData_proto_goTypes,
		DependencyIndexes: file_table_PlayerData_proto_depIdxs,
		MessageInfos:      file_table_PlayerData_proto_msgTypes,
	}.Build()
	File_table_PlayerData_proto = out.File
	file_table_PlayerData_proto_rawDesc = nil
	file_table_PlayerData_proto_goTypes = nil
	file_table_PlayerData_proto_depIdxs = nil
}
