// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v4.23.4
// source: Cmd.proto

package protobufMsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMD int32

const (
	CMD_null   CMD = 0
	CMD_Login  CMD = 100 //登录协议
	CMD_Login2 CMD = 101 //登录协议1
	CMD_Login3 CMD = 102 //登录协议2
	CMD_Login4 CMD = 103 //登录协议3
	// //////////////////////////////msgId 10000 -- 20000 之间的是server之间的消息号，客户端不占用///////////////////////////////////////
	CMD_Server2Server CMD = 10000 //server2server 服务器之间通信的消息号
	CMD_MaxServeMsgId CMD = 20000 //maxServeMsgId 服务器之间通信消息号最大值
)

// Enum value maps for CMD.
var (
	CMD_name = map[int32]string{
		0:     "null",
		100:   "Login",
		101:   "Login2",
		102:   "Login3",
		103:   "Login4",
		10000: "Server2Server",
		20000: "MaxServeMsgId",
	}
	CMD_value = map[string]int32{
		"null":          0,
		"Login":         100,
		"Login2":        101,
		"Login3":        102,
		"Login4":        103,
		"Server2Server": 10000,
		"MaxServeMsgId": 20000,
	}
)

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}

func (x CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_Cmd_proto_enumTypes[0].Descriptor()
}

func (CMD) Type() protoreflect.EnumType {
	return &file_Cmd_proto_enumTypes[0]
}

func (x CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD.Descriptor instead.
func (CMD) EnumDescriptor() ([]byte, []int) {
	return file_Cmd_proto_rawDescGZIP(), []int{0}
}

var File_Cmd_proto protoreflect.FileDescriptor

var file_Cmd_proto_rawDesc = []byte{
	0x0a, 0x09, 0x43, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x67, 0x0a, 0x03, 0x43,
	0x4d, 0x44, 0x12, 0x08, 0x0a, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x64, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x32, 0x10, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x33, 0x10, 0x66, 0x12,
	0x0a, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x34, 0x10, 0x67, 0x12, 0x12, 0x0a, 0x0d, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x32, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x10, 0x90, 0x4e, 0x12,
	0x13, 0x0a, 0x0d, 0x4d, 0x61, 0x78, 0x53, 0x65, 0x72, 0x76, 0x65, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x10, 0xa0, 0x9c, 0x01, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Cmd_proto_rawDescOnce sync.Once
	file_Cmd_proto_rawDescData = file_Cmd_proto_rawDesc
)

func file_Cmd_proto_rawDescGZIP() []byte {
	file_Cmd_proto_rawDescOnce.Do(func() {
		file_Cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_Cmd_proto_rawDescData)
	})
	return file_Cmd_proto_rawDescData
}

var file_Cmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Cmd_proto_goTypes = []any{
	(CMD)(0), // 0: CMD
}
var file_Cmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Cmd_proto_init() }
func file_Cmd_proto_init() {
	if File_Cmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Cmd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Cmd_proto_goTypes,
		DependencyIndexes: file_Cmd_proto_depIdxs,
		EnumInfos:         file_Cmd_proto_enumTypes,
	}.Build()
	File_Cmd_proto = out.File
	file_Cmd_proto_rawDesc = nil
	file_Cmd_proto_goTypes = nil
	file_Cmd_proto_depIdxs = nil
}
