// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.1
// source: Server.proto

package protobufMsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务器间通信协议负载消息的类型
type ServerMsgType int32

const (
	ServerMsgType_protobufMsg ServerMsgType = 0 // protobuf  消息
	ServerMsgType_structMsg   ServerMsgType = 1 // go 结构体消息
)

// Enum value maps for ServerMsgType.
var (
	ServerMsgType_name = map[int32]string{
		0: "protobufMsg",
		1: "structMsg",
	}
	ServerMsgType_value = map[string]int32{
		"protobufMsg": 0,
		"structMsg":   1,
	}
)

func (x ServerMsgType) Enum() *ServerMsgType {
	p := new(ServerMsgType)
	*p = x
	return p
}

func (x ServerMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_Server_proto_enumTypes[0].Descriptor()
}

func (ServerMsgType) Type() protoreflect.EnumType {
	return &file_Server_proto_enumTypes[0]
}

func (x ServerMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerMsgType.Descriptor instead.
func (ServerMsgType) EnumDescriptor() ([]byte, []int) {
	return file_Server_proto_rawDescGZIP(), []int{0}
}

// 服务器间通信协议
type CsServer2Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ServerMsgType `protobuf:"varint,1,opt,name=type,proto3,enum=ServerMsgType" json:"type,omitempty"`
	Cmd  int32         `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"` //protobufMsg 则为 消息号 ；  structMsg 则为 结构体定义的枚举号
	Data []byte        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CsServer2Server) Reset() {
	*x = CsServer2Server{}
	mi := &file_Server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsServer2Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsServer2Server) ProtoMessage() {}

func (x *CsServer2Server) ProtoReflect() protoreflect.Message {
	mi := &file_Server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsServer2Server.ProtoReflect.Descriptor instead.
func (*CsServer2Server) Descriptor() ([]byte, []int) {
	return file_Server_proto_rawDescGZIP(), []int{0}
}

func (x *CsServer2Server) GetType() ServerMsgType {
	if x != nil {
		return x.Type
	}
	return ServerMsgType_protobufMsg
}

func (x *CsServer2Server) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *CsServer2Server) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 服务器间通信协议
type ScServer2Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type ServerMsgType `protobuf:"varint,1,opt,name=type,proto3,enum=ServerMsgType" json:"type,omitempty"`
	Cmd  int32         `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"` //protobufMsg 则为 消息号 ；  structMsg 则为 结构体定义的枚举号
	Data []byte        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ScServer2Server) Reset() {
	*x = ScServer2Server{}
	mi := &file_Server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScServer2Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScServer2Server) ProtoMessage() {}

func (x *ScServer2Server) ProtoReflect() protoreflect.Message {
	mi := &file_Server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScServer2Server.ProtoReflect.Descriptor instead.
func (*ScServer2Server) Descriptor() ([]byte, []int) {
	return file_Server_proto_rawDescGZIP(), []int{1}
}

func (x *ScServer2Server) GetType() ServerMsgType {
	if x != nil {
		return x.Type
	}
	return ServerMsgType_protobufMsg
}

func (x *ScServer2Server) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *ScServer2Server) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_Server_proto protoreflect.FileDescriptor

var file_Server_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b,
	0x0a, 0x0f, 0x63, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x32, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5b, 0x0a, 0x0f, 0x73,
	0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x32, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x22,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x2f, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x73, 0x67, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x10, 0x01, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x73,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Server_proto_rawDescOnce sync.Once
	file_Server_proto_rawDescData = file_Server_proto_rawDesc
)

func file_Server_proto_rawDescGZIP() []byte {
	file_Server_proto_rawDescOnce.Do(func() {
		file_Server_proto_rawDescData = protoimpl.X.CompressGZIP(file_Server_proto_rawDescData)
	})
	return file_Server_proto_rawDescData
}

var file_Server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Server_proto_goTypes = []any{
	(ServerMsgType)(0),      // 0: ServerMsgType
	(*CsServer2Server)(nil), // 1: csServer2Server
	(*ScServer2Server)(nil), // 2: scServer2Server
}
var file_Server_proto_depIdxs = []int32{
	0, // 0: csServer2Server.type:type_name -> ServerMsgType
	0, // 1: scServer2Server.type:type_name -> ServerMsgType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Server_proto_init() }
func file_Server_proto_init() {
	if File_Server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Server_proto_goTypes,
		DependencyIndexes: file_Server_proto_depIdxs,
		EnumInfos:         file_Server_proto_enumTypes,
		MessageInfos:      file_Server_proto_msgTypes,
	}.Build()
	File_Server_proto = out.File
	file_Server_proto_rawDesc = nil
	file_Server_proto_goTypes = nil
	file_Server_proto_depIdxs = nil
}
